CafeEmployees/Models/CafeRepository.cs
using CafeEmployees.Models;
using Dapper;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;

namespace CafeEmployees.Models
{
    public class CafeRepository
    {
        private static readonly string ConnectionString = @"Data Source=MacBook-Air-Olga.local;Initial Catalog=cafe_employees;Integrated Security=True";
        public static List<EmployeeModel> GetEmployees()
        {
            using (IDbConnection db = new SqlConnection(ConnectionString))
            {
                return db.Query<EmployeeModel>("SELECT * FROM Employees").ToList();
            }
        }

        public static EmployeeModel Get(int id)
        {
            using (IDbConnection db = new SqlConnection(ConnectionString))
            {
                return db.Query<EmployeeModel>("SELECT * FROM Employees WHERE Id = @id", new { id }).FirstOrDefault();
            }
        }

        public static void Create(EmployeeModel employee)
        {
            using (IDbConnection db = new SqlConnection(ConnectionString))
            {
                var sqlQuery = "INSERT INTO Employees (Name, Age) VALUES(@Name, @Age)";
                db.Execute(sqlQuery, employee);

                // если мы хотим получить id добавленного пользователя
                //var sqlQuery = "INSERT INTO Users (Name, Age) VALUES(@Name, @Age); SELECT CAST(SCOPE_IDENTITY() as int)";
                //int? employeeId = db.Query<int>(sqlQuery, employee).FirstOrDefault();
                //employee.Id = employeeId.Value;
            }
        }

        public static void Update(EmployeeModel employee)
        {
            using (IDbConnection db = new SqlConnection(ConnectionString))
            {
                var sqlQuery = "UPDATE Employees SET Name = @Name, Age = @Age WHERE Id = @Id";
                db.Execute(sqlQuery, employee);
            }
        }

        public static void Delete(int id)
        {
            using (IDbConnection db = new SqlConnection(ConnectionString))
            {
                var sqlQuery = "DELETE FROM Employees WHERE Id = @id";
                db.Execute(sqlQuery, new { id });
            }
        }
    }
}

CafeEmployees/Models/EmployeeModel.cs
using System;

namespace CafeEmployees.Models
{
    public class EmployeeModel
    {
        private int Id { get; set; }
        private string Name { get; set; }
        private string Surname { get; set; }
        private DateTime DataOfBirth { get; set; }
        private int Phone { get; set; }
        private int Passport { get; set; }
        private int QualificationId { get; set; }
    }
}

CafeEmployees/Models/QualificationModel.cs
namespace CafeEmployees.Models
{
    public class QualificationModel
    {
        private int Id { get; set; }
        private string Name { get; set; }
        private int Salary { get; set; }
    }
}

CafeEmployees/Models/WorkingProcessModel.cs
using System;

namespace CafeEmployees.Models
{
    public class WorkingProcessModel
    {
        private int Id { get; set; }
        private int EmployeeId { get; set; }
        private DateTime Date { get; set; }
        private DateTime StartTime { get; set; }
        private DateTime EndTime { get; set; }
    }
}

CafeEmployees/Controllers/EmployeeController.cs
using System.Web.Mvc;

namespace CafeEmployees.Controllers
{
    public class EmployeeController : Controller
    {
        // GET
        public ActionResult Index()
        {
            return View();
        }
    }
}

CafeEmployees/Controllers/HomeController.cs
using System.Web.Mvc;

namespace CafeEmployees.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

CafeEmployees/Controllers/QualificationController.cs
using System.Web.Mvc;

namespace CafeEmployees.Controllers
{
    public class QualificationController : Controller
    {
        // GET
        public ActionResult Index()
        {
            return View();
        }
    }
}

CafeEmployees/Controllers/SalaryController.cs
using System.Web.Mvc;

namespace CafeEmployees.Controllers
{
    public class SalaryController : Controller
    {
        // GET
        public ActionResult Index()
        {
            return View();
        }
    }
}

CafeEmployees/Controllers/WorkingProcessController.cs
using System.Web.Mvc;

namespace CafeEmployees.Controllers
{
    public class WorkingProcessController : Controller
    {
        // GET
        public ActionResult Index()
        {
            return View();
        }
    }
}

CafeEmployees/Views/Employee/Index.cshtml
@{
    ViewBag.Title = "Список сотрудников";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h2>@ViewBag.Title</h2>
    <form>
        <h4>Добавление нового сотрудника</h4>
        <p>
            <input type="text" name="Surname" placeholder="Фамилия">
            <input type="text" name="Name" placeholder="Имя">
            Дата рождения: <input type="date" name="Birth">
            <input type="text" name="Phone" placeholder="Телефон">
            <input type="text" name="Passport" placeholder="Паспорт">
            <select name="Qualification">
                <option>Специальность</option>
                <option>Администратор</option>
                <option>Бармен</option>
                <option>Официант</option>
            </select>
            <input type="submit" value="Добавить">
        </p>
    </form>
    <table class="table">
        <tr>
            <td><p>Фамилия</p></td>
            <td><p>Имя</p></td>
            <td><p>Дата рождения</p></td>
            <td><p>Телефон</p></td>
            <td><p>Паспорт</p></td>
            <td><p>Специальность</p></td>
            <td></td>
        </tr>
        <tr>
            <td><p>Горбачева</p></td>
            <td><p>Ольга</p></td>
            <td><p>18.11.2000</p></td>
            <td><p>89003158860</p></td>
            <td><p>5614253803</p></td>
            <td><p>Официант</p></td>
            <td></td>
        </tr>
        <tr>
            <td><p>Испольнов</p></td>
            <td><p>Кирилл</p></td>
            <td><p>15.11.2000</p></td>
            <td><p>89563214568</p></td>
            <td><p>5416235689</p></td>
            <td><p>Бармен</p></td>
            <td></td>
        </tr>
        <tr>
            <td><p>Цыбарева</p></td>
            <td><p>Кристина</p></td>
            <td><p>23.03.1993</p></td>
            <td><p>89436758904</p></td>
            <td><p>5513236457</p></td>
            <td><p>Администратор</p></td>
            <td></td>
        </tr>
    </table>
</div>

CafeEmployees/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная";
}

<div class="jumbotron">
    <h1>Добро пожаловать в систему управления сотрудниками!</h1>
    <p class="lead">Данное приложение разработано с целью упростить учет рабочего времени и расчет заработной платы
        сотрудников вашего предприятия</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Таблица сотрудников</h2>
        <p>В любое время вы имеете доступ к данным о сотрудниках</p>
    </div>
    <div class="col-md-4">
        <h2>Наименование специальностей</h2>
        <p>Добавляйте, редактируйте, удаляйте специальности, профессии и квалификации в зависимости от структуры Вашего предприятия</p>
    </div>
    <div class="col-md-4">
        <h2>Расчет заработной платы</h2>
        <p>Вносите параметры расчета заработной платы - мы посчитаем за пару секунд!</p>
    </div>
</div>

CafeEmployees/Views/Qualification/Index.cshtml
@model CafeEmployees.Models.QualificationModel
@{
    ViewBag.Title = "Таблица специальностей";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h2>Таблица специальностей</h2>
    <form class="form-control-static">
        <h4>Добавление новой специальности</h4>
        <p>
            <input type="text" name="Name" placeholder="Наименование" style="width: 210px;">
            <input type="number" name="Salary" placeholder="Размер почасовой оплаты" style="width: 210px;">
            <input type="submit" value="Добавить">
        </p>
    </form>
    <table class="table">
        <tr>
            <td><p>Наименование</p></td>
            <td><p>Размер почасовой оплаты (руб/час)</p></td>
            <td></td>
        </tr>
        <tr>
            <td><p>Администратор</p></td>
            <td><p>120</p></td>
            <td></td>
        </tr>
        <tr>
            <td><p>Бармен</p></td>
            <td><p>100</p></td>
            <td></td>
        </tr>
        <tr>
            <td><p>Официант</p></td>
            <td><p>80</p></td>
            <td></td>
        </tr>
    </table>
</div>

CafeEmployees/Views/Salary/Index.cshtml
@{
    ViewBag.Title = "Расчет заработной платы";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h2>@ViewBag.Title</h2>
    <form class="form-control-static">
        <p>
            <select name="Employee">
                <option>Сотрудник</option>
                <option>Горбачева Ольга</option>
                <option>Испольнов Кирилл</option>
                <option>Цыбарева Кристина</option>
            </select>
            Время начала работы: <input type="datetime" name="StartTime">
            Время окончания работы: <input type="datetime" name="EndTime">
            <input type="submit" value="Рассчитать">
        </p>
        <p>
            Отработано за период: 10 часов, к оплате: 800 рублей
        </p>
    </form>
</div>

CafeEmployees/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Сотрудники", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Специальности", "Index", "Qualification")</li>
                    <li>@Html.ActionLink("Рабочий процесс", "Index", "WorkingProcess")</li>
                    <li>@Html.ActionLink("Заработная плата", "Index", "Salary")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Gorbacheva Olga, 2019</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CafeEmployees/Views/WorkingProcess/Index.cshtml
@model CafeEmployees.Models.WorkingProcessModel

@{
    ViewBag.Title = "Таблица рабочего времени";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h2>@ViewBag.Title</h2>
    <form class="form-control-static">
        <h4>Добавление новой позиции</h4>
        <p>
            <select name="Employee">
                <option>Сотрудник</option>
                <option>Горбачева Ольга</option>
                <option>Испольнов Кирилл</option>
                <option>Цыбарева Кристина</option>
            </select>
            Время начала работы: <input type="datetime" name="StartTime">
            Время окончания работы: <input type="datetime" name="EndTime">
            <input type="submit" value="Добавить">
        </p>
    </form>
    <table class="table">
        <tr>
            <td><p>Сотрудник</p></td>
            <td><p>Время начала работы</p></td>
            <td><p>Время окончания работы</p></td>
        </tr>
        <tr>
            <td><p>Испольнов Кирилл</p></td>
            <td><p>09.11.2019 09:00</p></td>
            <td><p>09.11.2019 20:00</p></td>
        </tr>
        <tr>
            <td><p>Горбачева Ольга</p></td>
            <td><p>12.11.2019 12:00</p></td>
            <td><p>12.11.2019 22:00</p></td>
        </tr>
        <tr>
            <td><p>Цыбарева Кристина</p></td>
            <td><p>10.11.2019 17:00</p></td>
            <td><p>11.11.2019 02:00</p></td>
        </tr>
    </table>
</div>